### PR TITLE
Ukrainian translation

### PR DESCRIPTION
**Pull request by VovaMobile**
Hi, this is an Ukrainian translation for Kill Process addon

### CODE REVIEW

**Comment by rayo-alcantar** [comment]
ello! Thank you very much for the translation. It was added to the latest commit made. As I am a beginner in creating addons and honestly did not expect someone to want to translate it, it raises a couple of doubts on how to proceed from this point.
Should I pass you the texts somewhere? For the documentation, is it the same? What is the process?
Sorry for the inconvenience and for my english.

**Comment by VovaMobile** [comment]
Hello.
First, I downloaded the addon repository via Github.
Then, using Poedit, I extracted the strings for translation from the
KillProcess.py and buildVars.py files. At first, I tried to get the
strings with the scons pot command, but this command only extracted
strings from the buildVars.py file.
I translated the documentation directly from Spanish using Deepl, but
this translation is not perfect, so I corrected it, as I have
extensive experience in translating and testing addons for NVDA.
Then I created the appropriate folder structure and the translation was ready.
To find out how to make it possible for scons pot to extract strings
for translation, please consult with experienced addon developers.

2023-07-21 18:38 GMT+03:00, Ángel Alcántar ***@***.***>:

**Comment by rayo-alcantar** [comment]
Thank you so much!
But my specific question was about continuing the translation. That is, I need to share with you in some way the new strings that I add (if I do) and in the case of the documentation, I imagine you will take it from GitHub, right?
Again, I apologize for my English and my lack of experience.
Still, the translation has already been added.

**Comment by VovaMobile** [comment]
Yes, you can share the new pot-file  with me so that I can update the
current translation from it.
I can also get new strings by checking for strings updates manually,
but that doesn't guarantee that the translations will be timely in
that case.

2023-07-22 2:37 GMT+03:00, Ángel Alcántar ***@***.***>:

**Comment by rayo-alcantar** [comment]
Understood, thank you very much.
I don't think I'll add new strings, at least not in the near future. On the other hand, in the case of the documentation and the MD files, would you update based on the commits and changes I make? Or do I need to do some extra action?

**Comment by VovaMobile** [comment]
I'll make changes based on your changes.

2023-07-22 17:17 GMT+03:00, Ángel Alcántar ***@***.***>:

**Pull request merged**
